<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Blossom.Classroom.Protocol.Tests</RootNamespace>
    <AssemblyName>Classroom.Protocol.Tests</AssemblyName>
    <Version>0.1.0-dev</Version>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Classroom.Protocol\Classroom.Protocol.csproj" />
  </ItemGroup>
</Project>

