<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>PhoneUnlock.Setup</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PhoneUnlock.Core\PhoneUnlock.Core.csproj" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
  </ItemGroup>
</Project>
