<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Blossom.Classroom.Core.Tests</RootNamespace>
    <AssemblyName>Classroom.Core.Tests</AssemblyName>
    <Version>0.1.0-dev</Version>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Classroom.Core\Classroom.Core.csproj" />
  </ItemGroup>
</Project>

